# Generated by Django 5.2.2 on 2025-06-07 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosTurismoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2050)], verbose_name='Ano de referência')),
                ('viagens_domesticas', models.PositiveIntegerField(help_text='Número total de viagens domésticas para o DF', verbose_name='Viagens domésticas (em milhares)')),
                ('variacao_viagens', models.FloatField(help_text='Variação em relação ao ano anterior (%)', verbose_name='Variação percentual de viagens')),
                ('gasto_medio', models.DecimalField(decimal_places=2, help_text='Gasto médio por viagem com pernoite', max_digits=10, verbose_name='Gasto médio por viagem (R$)')),
                ('motivo_lazer', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Viagens por lazer (%)')),
                ('motivo_visita', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Viagens para visitar familiares/eventos (%)')),
                ('motivo_saude', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Viagens para tratamento de saúde (%)')),
                ('motivo_outros', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Outros motivos de viagem (%)')),
                ('transporte_carro', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Uso de carro particular/empresa (%)')),
                ('transporte_aviao', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Uso de avião (%)')),
                ('transporte_onibus_excursao', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Uso de ônibus de excursão/fretado (%)')),
                ('transporte_onibus_linha', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Uso de ônibus de linha (%)')),
                ('transporte_outros', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Outros meios de transporte (%)')),
                ('turistas_internacionais', models.PositiveIntegerField(verbose_name='Turistas estrangeiros (em milhares)')),
                ('variacao_internacional', models.FloatField(verbose_name='Variação turismo internacional (%)')),
                ('ocupacao_hoteleira', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taxa de ocupação hoteleira (%)')),
                ('contribuicao_pib', models.FloatField(verbose_name='Contribuição para o PIB do DF (%)')),
                ('arrecadacao_iss', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Arrecadação de ISS (em milhões R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dados Anuais de Turismo',
                'verbose_name_plural': 'Dados Anuais de Turismo',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='EventoDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('FEIRA', 'Feira/Exposição'), ('ESPORTE', 'Evento Esportivo'), ('SHOW', 'Show/Espetáculo'), ('CONGRESSO', 'Congresso/Convenção'), ('OUTRO', 'Outro')], max_length=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('visitantes_estimados', models.PositiveIntegerField()),
                ('impacto_economico', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Impacto econômico (R$)')),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Evento de Destaque',
                'verbose_name_plural': 'Eventos de Destaque',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PaisEmissor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('posicao_ranking', models.PositiveIntegerField()),
                ('percentual', models.FloatField(help_text='Percentual do total de turistas internacionais', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'País Emissor',
                'verbose_name_plural': 'Países Emissores',
                'ordering': ['posicao_ranking'],
            },
        ),
        migrations.CreateModel(
            name='RotaAerea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('ativa', models.BooleanField(default=True)),
                ('data_inicio', models.DateField()),
                ('voos_semanais', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Rota Aérea Internacional',
                'verbose_name_plural': 'Rotas Aéreas Internacionais',
                'ordering': ['pais', 'destino'],
            },
        ),
        migrations.DeleteModel(
            name='Relatorio',
        ),
    ]
