# Generated by Django 5.2.1 on 2025-06-01 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turista',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Turista', 'verbose_name_plural': 'Turistas'},
        ),
        migrations.RenameField(
            model_name='turista',
            old_name='data_cadastro',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='turista',
            name='ativo',
        ),
        migrations.AddField(
            model_name='turista',
            name='cidade_origem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='turista',
            name='data_nascimento',
            field=models.DateField(default='2004-12-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turista',
            name='data_visita',
            field=models.DateField(default='2025-05-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turista',
            name='email',
            field=models.EmailField(default='viniciusvicente@teste.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turista',
            name='nome_completo',
            field=models.CharField(default='Vinicius Amorim Vicente de Sousa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turista',
            name='telefone',
            field=models.CharField(default='61 1234-5678', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turista',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turistas', to=settings.AUTH_USER_MODEL),
        ),
    ]
