# Generated by Django 5.2.2 on 2025-06-07 19:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CRIAR', 'Criação'), ('EDITAR', 'Edição'), ('EXCLUIR', 'Exclusão'), ('ERRO', 'Erro')], max_length=7)),
                ('modelo', models.CharField(max_length=50)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('mensagem', models.TextField()),
                ('ip', models.GenericIPAddressField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'logs_entry',
                'ordering': ['-data_hora'],
            },
        ),
    ]
